*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSA17_SCARR....................................*
FORM GET_DATA_ZVSA17_SCARR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSCARR_A17 WHERE
(VIM_WHERETAB) .
    CLEAR ZVSA17_SCARR .
ZVSA17_SCARR-MANDT =
ZTSCARR_A17-MANDT .
ZVSA17_SCARR-CARRID =
ZTSCARR_A17-CARRID .
ZVSA17_SCARR-CARRNAME =
ZTSCARR_A17-CARRNAME .
ZVSA17_SCARR-CURRCODE =
ZTSCARR_A17-CURRCODE .
ZVSA17_SCARR-URL =
ZTSCARR_A17-URL .
<VIM_TOTAL_STRUC> = ZVSA17_SCARR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSA17_SCARR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSA17_SCARR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSA17_SCARR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSCARR_A17 WHERE
  CARRID = ZVSA17_SCARR-CARRID .
    IF SY-SUBRC = 0.
    DELETE ZTSCARR_A17 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSCARR_A17 WHERE
  CARRID = ZVSA17_SCARR-CARRID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSCARR_A17.
    ENDIF.
ZTSCARR_A17-MANDT =
ZVSA17_SCARR-MANDT .
ZTSCARR_A17-CARRID =
ZVSA17_SCARR-CARRID .
ZTSCARR_A17-CARRNAME =
ZVSA17_SCARR-CARRNAME .
ZTSCARR_A17-CURRCODE =
ZVSA17_SCARR-CURRCODE .
ZTSCARR_A17-URL =
ZVSA17_SCARR-URL .
    IF SY-SUBRC = 0.
    UPDATE ZTSCARR_A17 ##WARN_OK.
    ELSE.
    INSERT ZTSCARR_A17 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSA17_SCARR-UPD_FLAG,
STATUS_ZVSA17_SCARR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSA17_SCARR.
  SELECT SINGLE * FROM ZTSCARR_A17 WHERE
CARRID = ZVSA17_SCARR-CARRID .
ZVSA17_SCARR-MANDT =
ZTSCARR_A17-MANDT .
ZVSA17_SCARR-CARRID =
ZTSCARR_A17-CARRID .
ZVSA17_SCARR-CARRNAME =
ZTSCARR_A17-CARRNAME .
ZVSA17_SCARR-CURRCODE =
ZTSCARR_A17-CURRCODE .
ZVSA17_SCARR-URL =
ZTSCARR_A17-URL .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSA17_SCARR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSA17_SCARR-CARRID TO
ZTSCARR_A17-CARRID .
MOVE ZVSA17_SCARR-MANDT TO
ZTSCARR_A17-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSCARR_A17'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSCARR_A17 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSCARR_A17'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVSA17_SFLIGHT..................................*
FORM GET_DATA_ZVSA17_SFLIGHT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSFLIGHT_A17 WHERE
(VIM_WHERETAB) .
    CLEAR ZVSA17_SFLIGHT .
ZVSA17_SFLIGHT-MANDT =
ZTSFLIGHT_A17-MANDT .
ZVSA17_SFLIGHT-CARRID =
ZTSFLIGHT_A17-CARRID .
ZVSA17_SFLIGHT-CONNID =
ZTSFLIGHT_A17-CONNID .
ZVSA17_SFLIGHT-FLDATE =
ZTSFLIGHT_A17-FLDATE .
ZVSA17_SFLIGHT-PRICE =
ZTSFLIGHT_A17-PRICE .
ZVSA17_SFLIGHT-CURRENCY =
ZTSFLIGHT_A17-CURRENCY .
ZVSA17_SFLIGHT-PLANETYPE =
ZTSFLIGHT_A17-PLANETYPE .
ZVSA17_SFLIGHT-SEATSMAX =
ZTSFLIGHT_A17-SEATSMAX .
ZVSA17_SFLIGHT-SEATSOCC =
ZTSFLIGHT_A17-SEATSOCC .
ZVSA17_SFLIGHT-PAYMENTSUM =
ZTSFLIGHT_A17-PAYMENTSUM .
ZVSA17_SFLIGHT-SEATSMAX_B =
ZTSFLIGHT_A17-SEATSMAX_B .
ZVSA17_SFLIGHT-SEATSOCC_B =
ZTSFLIGHT_A17-SEATSOCC_B .
ZVSA17_SFLIGHT-SEATSMAX_F =
ZTSFLIGHT_A17-SEATSMAX_F .
ZVSA17_SFLIGHT-SEATSOCC_F =
ZTSFLIGHT_A17-SEATSOCC_F .
<VIM_TOTAL_STRUC> = ZVSA17_SFLIGHT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSA17_SFLIGHT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSA17_SFLIGHT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSA17_SFLIGHT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSFLIGHT_A17 WHERE
  CARRID = ZVSA17_SFLIGHT-CARRID AND
  CONNID = ZVSA17_SFLIGHT-CONNID AND
  FLDATE = ZVSA17_SFLIGHT-FLDATE .
    IF SY-SUBRC = 0.
    DELETE ZTSFLIGHT_A17 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSFLIGHT_A17 WHERE
  CARRID = ZVSA17_SFLIGHT-CARRID AND
  CONNID = ZVSA17_SFLIGHT-CONNID AND
  FLDATE = ZVSA17_SFLIGHT-FLDATE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSFLIGHT_A17.
    ENDIF.
ZTSFLIGHT_A17-MANDT =
ZVSA17_SFLIGHT-MANDT .
ZTSFLIGHT_A17-CARRID =
ZVSA17_SFLIGHT-CARRID .
ZTSFLIGHT_A17-CONNID =
ZVSA17_SFLIGHT-CONNID .
ZTSFLIGHT_A17-FLDATE =
ZVSA17_SFLIGHT-FLDATE .
ZTSFLIGHT_A17-PRICE =
ZVSA17_SFLIGHT-PRICE .
ZTSFLIGHT_A17-CURRENCY =
ZVSA17_SFLIGHT-CURRENCY .
ZTSFLIGHT_A17-PLANETYPE =
ZVSA17_SFLIGHT-PLANETYPE .
ZTSFLIGHT_A17-SEATSMAX =
ZVSA17_SFLIGHT-SEATSMAX .
ZTSFLIGHT_A17-SEATSOCC =
ZVSA17_SFLIGHT-SEATSOCC .
ZTSFLIGHT_A17-PAYMENTSUM =
ZVSA17_SFLIGHT-PAYMENTSUM .
ZTSFLIGHT_A17-SEATSMAX_B =
ZVSA17_SFLIGHT-SEATSMAX_B .
ZTSFLIGHT_A17-SEATSOCC_B =
ZVSA17_SFLIGHT-SEATSOCC_B .
ZTSFLIGHT_A17-SEATSMAX_F =
ZVSA17_SFLIGHT-SEATSMAX_F .
ZTSFLIGHT_A17-SEATSOCC_F =
ZVSA17_SFLIGHT-SEATSOCC_F .
    IF SY-SUBRC = 0.
    UPDATE ZTSFLIGHT_A17 ##WARN_OK.
    ELSE.
    INSERT ZTSFLIGHT_A17 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSA17_SFLIGHT-UPD_FLAG,
STATUS_ZVSA17_SFLIGHT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSA17_SFLIGHT.
  SELECT SINGLE * FROM ZTSFLIGHT_A17 WHERE
CARRID = ZVSA17_SFLIGHT-CARRID AND
CONNID = ZVSA17_SFLIGHT-CONNID AND
FLDATE = ZVSA17_SFLIGHT-FLDATE .
ZVSA17_SFLIGHT-MANDT =
ZTSFLIGHT_A17-MANDT .
ZVSA17_SFLIGHT-CARRID =
ZTSFLIGHT_A17-CARRID .
ZVSA17_SFLIGHT-CONNID =
ZTSFLIGHT_A17-CONNID .
ZVSA17_SFLIGHT-FLDATE =
ZTSFLIGHT_A17-FLDATE .
ZVSA17_SFLIGHT-PRICE =
ZTSFLIGHT_A17-PRICE .
ZVSA17_SFLIGHT-CURRENCY =
ZTSFLIGHT_A17-CURRENCY .
ZVSA17_SFLIGHT-PLANETYPE =
ZTSFLIGHT_A17-PLANETYPE .
ZVSA17_SFLIGHT-SEATSMAX =
ZTSFLIGHT_A17-SEATSMAX .
ZVSA17_SFLIGHT-SEATSOCC =
ZTSFLIGHT_A17-SEATSOCC .
ZVSA17_SFLIGHT-PAYMENTSUM =
ZTSFLIGHT_A17-PAYMENTSUM .
ZVSA17_SFLIGHT-SEATSMAX_B =
ZTSFLIGHT_A17-SEATSMAX_B .
ZVSA17_SFLIGHT-SEATSOCC_B =
ZTSFLIGHT_A17-SEATSOCC_B .
ZVSA17_SFLIGHT-SEATSMAX_F =
ZTSFLIGHT_A17-SEATSMAX_F .
ZVSA17_SFLIGHT-SEATSOCC_F =
ZTSFLIGHT_A17-SEATSOCC_F .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSA17_SFLIGHT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSA17_SFLIGHT-CARRID TO
ZTSFLIGHT_A17-CARRID .
MOVE ZVSA17_SFLIGHT-CONNID TO
ZTSFLIGHT_A17-CONNID .
MOVE ZVSA17_SFLIGHT-FLDATE TO
ZTSFLIGHT_A17-FLDATE .
MOVE ZVSA17_SFLIGHT-MANDT TO
ZTSFLIGHT_A17-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSFLIGHT_A17'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSFLIGHT_A17 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSFLIGHT_A17'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVSA17_SPFLI....................................*
FORM GET_DATA_ZVSA17_SPFLI.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSPFLI_A17 WHERE
(VIM_WHERETAB) .
    CLEAR ZVSA17_SPFLI .
ZVSA17_SPFLI-MANDT =
ZTSPFLI_A17-MANDT .
ZVSA17_SPFLI-CARRID =
ZTSPFLI_A17-CARRID .
ZVSA17_SPFLI-CONNID =
ZTSPFLI_A17-CONNID .
ZVSA17_SPFLI-COUNTRYFR =
ZTSPFLI_A17-COUNTRYFR .
ZVSA17_SPFLI-CITYFROM =
ZTSPFLI_A17-CITYFROM .
ZVSA17_SPFLI-AIRPFROM =
ZTSPFLI_A17-AIRPFROM .
ZVSA17_SPFLI-COUNTRYTO =
ZTSPFLI_A17-COUNTRYTO .
ZVSA17_SPFLI-CITYTO =
ZTSPFLI_A17-CITYTO .
ZVSA17_SPFLI-AIRPTO =
ZTSPFLI_A17-AIRPTO .
ZVSA17_SPFLI-FLTIME =
ZTSPFLI_A17-FLTIME .
ZVSA17_SPFLI-DEPTIME =
ZTSPFLI_A17-DEPTIME .
ZVSA17_SPFLI-ARRTIME =
ZTSPFLI_A17-ARRTIME .
ZVSA17_SPFLI-DISTANCE =
ZTSPFLI_A17-DISTANCE .
ZVSA17_SPFLI-DISTID =
ZTSPFLI_A17-DISTID .
ZVSA17_SPFLI-FLTYPE =
ZTSPFLI_A17-FLTYPE .
ZVSA17_SPFLI-PERIOD =
ZTSPFLI_A17-PERIOD .
<VIM_TOTAL_STRUC> = ZVSA17_SPFLI.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSA17_SPFLI .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSA17_SPFLI.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSA17_SPFLI-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSPFLI_A17 WHERE
  CARRID = ZVSA17_SPFLI-CARRID AND
  CONNID = ZVSA17_SPFLI-CONNID .
    IF SY-SUBRC = 0.
    DELETE ZTSPFLI_A17 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSPFLI_A17 WHERE
  CARRID = ZVSA17_SPFLI-CARRID AND
  CONNID = ZVSA17_SPFLI-CONNID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSPFLI_A17.
    ENDIF.
ZTSPFLI_A17-MANDT =
ZVSA17_SPFLI-MANDT .
ZTSPFLI_A17-CARRID =
ZVSA17_SPFLI-CARRID .
ZTSPFLI_A17-CONNID =
ZVSA17_SPFLI-CONNID .
ZTSPFLI_A17-COUNTRYFR =
ZVSA17_SPFLI-COUNTRYFR .
ZTSPFLI_A17-CITYFROM =
ZVSA17_SPFLI-CITYFROM .
ZTSPFLI_A17-AIRPFROM =
ZVSA17_SPFLI-AIRPFROM .
ZTSPFLI_A17-COUNTRYTO =
ZVSA17_SPFLI-COUNTRYTO .
ZTSPFLI_A17-CITYTO =
ZVSA17_SPFLI-CITYTO .
ZTSPFLI_A17-AIRPTO =
ZVSA17_SPFLI-AIRPTO .
ZTSPFLI_A17-FLTIME =
ZVSA17_SPFLI-FLTIME .
ZTSPFLI_A17-DEPTIME =
ZVSA17_SPFLI-DEPTIME .
ZTSPFLI_A17-ARRTIME =
ZVSA17_SPFLI-ARRTIME .
ZTSPFLI_A17-DISTANCE =
ZVSA17_SPFLI-DISTANCE .
ZTSPFLI_A17-DISTID =
ZVSA17_SPFLI-DISTID .
ZTSPFLI_A17-FLTYPE =
ZVSA17_SPFLI-FLTYPE .
ZTSPFLI_A17-PERIOD =
ZVSA17_SPFLI-PERIOD .
    IF SY-SUBRC = 0.
    UPDATE ZTSPFLI_A17 ##WARN_OK.
    ELSE.
    INSERT ZTSPFLI_A17 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSA17_SPFLI-UPD_FLAG,
STATUS_ZVSA17_SPFLI-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVSA17_SPFLI.
  SELECT SINGLE * FROM ZTSPFLI_A17 WHERE
CARRID = ZVSA17_SPFLI-CARRID AND
CONNID = ZVSA17_SPFLI-CONNID .
ZVSA17_SPFLI-MANDT =
ZTSPFLI_A17-MANDT .
ZVSA17_SPFLI-CARRID =
ZTSPFLI_A17-CARRID .
ZVSA17_SPFLI-CONNID =
ZTSPFLI_A17-CONNID .
ZVSA17_SPFLI-COUNTRYFR =
ZTSPFLI_A17-COUNTRYFR .
ZVSA17_SPFLI-CITYFROM =
ZTSPFLI_A17-CITYFROM .
ZVSA17_SPFLI-AIRPFROM =
ZTSPFLI_A17-AIRPFROM .
ZVSA17_SPFLI-COUNTRYTO =
ZTSPFLI_A17-COUNTRYTO .
ZVSA17_SPFLI-CITYTO =
ZTSPFLI_A17-CITYTO .
ZVSA17_SPFLI-AIRPTO =
ZTSPFLI_A17-AIRPTO .
ZVSA17_SPFLI-FLTIME =
ZTSPFLI_A17-FLTIME .
ZVSA17_SPFLI-DEPTIME =
ZTSPFLI_A17-DEPTIME .
ZVSA17_SPFLI-ARRTIME =
ZTSPFLI_A17-ARRTIME .
ZVSA17_SPFLI-DISTANCE =
ZTSPFLI_A17-DISTANCE .
ZVSA17_SPFLI-DISTID =
ZTSPFLI_A17-DISTID .
ZVSA17_SPFLI-FLTYPE =
ZTSPFLI_A17-FLTYPE .
ZVSA17_SPFLI-PERIOD =
ZTSPFLI_A17-PERIOD .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSA17_SPFLI USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSA17_SPFLI-CARRID TO
ZTSPFLI_A17-CARRID .
MOVE ZVSA17_SPFLI-CONNID TO
ZTSPFLI_A17-CONNID .
MOVE ZVSA17_SPFLI-MANDT TO
ZTSPFLI_A17-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSPFLI_A17'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSPFLI_A17 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSPFLI_A17'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
