*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVSA17VEN.......................................*
FORM GET_DATA_ZVSA17VEN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTSA17VEN WHERE
(VIM_WHERETAB) .
    CLEAR ZVSA17VEN .
ZVSA17VEN-MANDT =
ZTSA17VEN-MANDT .
ZVSA17VEN-LIFNR =
ZTSA17VEN-LIFNR .
ZVSA17VEN-LAND1 =
ZTSA17VEN-LAND1 .
ZVSA17VEN-NAME1 =
ZTSA17VEN-NAME1 .
ZVSA17VEN-NAME2 =
ZTSA17VEN-NAME2 .
ZVSA17VEN-VENCA =
ZTSA17VEN-VENCA .
ZVSA17VEN-CARRID =
ZTSA17VEN-CARRID .
ZVSA17VEN-MEALNO =
ZTSA17VEN-MEALNO .
ZVSA17VEN-PRICE =
ZTSA17VEN-PRICE .
ZVSA17VEN-WAERS =
ZTSA17VEN-WAERS .
<VIM_TOTAL_STRUC> = ZVSA17VEN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVSA17VEN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVSA17VEN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVSA17VEN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTSA17VEN WHERE
  LIFNR = ZVSA17VEN-LIFNR .
    IF SY-SUBRC = 0.
    DELETE ZTSA17VEN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTSA17VEN WHERE
  LIFNR = ZVSA17VEN-LIFNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTSA17VEN.
    ENDIF.
ZTSA17VEN-MANDT =
ZVSA17VEN-MANDT .
ZTSA17VEN-LIFNR =
ZVSA17VEN-LIFNR .
ZTSA17VEN-LAND1 =
ZVSA17VEN-LAND1 .
ZTSA17VEN-NAME1 =
ZVSA17VEN-NAME1 .
ZTSA17VEN-NAME2 =
ZVSA17VEN-NAME2 .
ZTSA17VEN-VENCA =
ZVSA17VEN-VENCA .
ZTSA17VEN-CARRID =
ZVSA17VEN-CARRID .
ZTSA17VEN-MEALNO =
ZVSA17VEN-MEALNO .
ZTSA17VEN-PRICE =
ZVSA17VEN-PRICE .
ZTSA17VEN-WAERS =
ZVSA17VEN-WAERS .
    IF SY-SUBRC = 0.
    UPDATE ZTSA17VEN ##WARN_OK.
    ELSE.
    INSERT ZTSA17VEN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVSA17VEN-UPD_FLAG,
STATUS_ZVSA17VEN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVSA17VEN.
  SELECT SINGLE * FROM ZTSA17VEN WHERE
LIFNR = ZVSA17VEN-LIFNR .
ZVSA17VEN-MANDT =
ZTSA17VEN-MANDT .
ZVSA17VEN-LIFNR =
ZTSA17VEN-LIFNR .
ZVSA17VEN-LAND1 =
ZTSA17VEN-LAND1 .
ZVSA17VEN-NAME1 =
ZTSA17VEN-NAME1 .
ZVSA17VEN-NAME2 =
ZTSA17VEN-NAME2 .
ZVSA17VEN-VENCA =
ZTSA17VEN-VENCA .
ZVSA17VEN-CARRID =
ZTSA17VEN-CARRID .
ZVSA17VEN-MEALNO =
ZTSA17VEN-MEALNO .
ZVSA17VEN-PRICE =
ZTSA17VEN-PRICE .
ZVSA17VEN-WAERS =
ZTSA17VEN-WAERS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVSA17VEN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVSA17VEN-LIFNR TO
ZTSA17VEN-LIFNR .
MOVE ZVSA17VEN-MANDT TO
ZTSA17VEN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTSA17VEN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTSA17VEN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTSA17VEN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
